### DISCUSSION TITLE
Where is the config?

### DISCUSSION THREAD

**Discussion by EmilePapillon** [EmulatorJS/EmulatorJS#922] [General]
To give an idea, here's my compose.yaml

``` yaml
---
services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/rpi/emulatorjs/config:/config
      - /media/NEXTCLOUD/game/data:/data
    ports:
      - 3000:3000
      - 81:80
    restart: unless-stopped
```

the file `/home/rpi/emulatorjs/config` does not contain anything that seems meaningful: a profile directory, with a json file and a default config for retroarch that defines 2 options.

I'm wondering where does emulatorjs store things like my roms configs, the ones I see in the backend like:
```
 "Star Fox 2": {
      "has_logo": false,
      "has_video": false
    },
```

Where is that stored in the server? I have a game that I am unable to remove from the frontend, no matter what I do, it is not going away.
